# Generated by Django 3.1.4 on 2021-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_resizing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostCopy',
        ),
        migrations.DeleteModel(
            name='PostOrigin',
        ),
    ]
