# Generated by Django 3.1.4 on 2021-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_resizing', '0002_auto_20210123_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
